### PHASE 1 — Basic Authentication

### Phase 1 — Basic Auth (unauthenticated)
GET http://127.0.0.1:8000/api/basic/ HTTP/1.1

### Phase 1 — Basic Auth (with credentials)
GET http://127.0.0.1:8000/api/basic/ HTTP/1.1
Authorization: Basic YWRtaW46YWRtaW4xMjM=